### ISSUE TITLE
找不到其他方式联系作者。。。想请教作者是什么原因不处理多义词的呢？

### ISSUE THREAD

**Issue by yangershu** [Times125/baiduSpider#3]
我正在使用这个项目，很完善的项目；想请教作者，是什么原因不处理多义词的呢？百度百科其实会有非常多的多义词（特别是人物），不处理的话会丢失很多数据，麻烦告知。

**Comment by Times125** [comment]
> 会丢失很多数据，麻烦告知。

多义词也考虑了，嫌麻烦没弄，有时间我搞一搞
